/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function cancelJob(printerName: string, jobId: bigint): void

export declare function getActiveJobs(printerName: string): Array<PrinterJob>

export declare function getDefaultPrinter(): Printer | null

export declare function getJobHistory(printerName: string): Array<PrinterJob>

export declare function getPrinterByName(printerName: string): Printer | null

export declare function getPrinters(): Array<Printer>

export interface GhostscriptConfig {
  device: GhostscriptDevice
  dpi?: number
}

/**
 * Ghostscript output device for the optional pre-print converter.
 * Each variant maps to a `-sDEVICE=<name>` flag passed to the
 * `gs` / `gswin64c.exe` binary, which must be on PATH.
 */
export declare const enum GhostscriptDevice {
  /** PostScript level 2/3 — typical choice for PDF→PS before sending to a printer. */
  PS2WRITE = 'PS2WRITE',
  /** 24-bit RGB PNG raster. */
  PNG16M = 'PNG16M',
  /** TIFF group 4 (1-bit fax-style). */
  TIFFG4 = 'TIFFG4',
  /** 1-bit monochrome PNG. */
  PNGMONO = 'PNGMONO'
}

export declare function pauseJob(printerName: string, jobId: bigint): void

export declare function print(printerName: string, buffer: Uint8Array, jobName: string | undefined | null, options: Array<PrintOption>, ghostscript?: GhostscriptConfig | undefined | null): bigint

export interface Printer {
  name: string
  systemName: string
  driverName: string
  uri: string
  portName: string
  processor: string
  dataType: string
  description: string
  location: string
  isDefault: boolean
  isShared: boolean
  state: PrinterState
  stateReasons: Array<string>
}

export interface PrinterJob {
  id: bigint
  name: string
  state: PrinterJobState
  mediaType: string
  createdAt: Date
  processedAt?: Date
  completedAt?: Date
  printerName: string
}

export declare const enum PrinterJobState {
  PENDING = 'PENDING',
  PAUSED = 'PAUSED',
  PROCESSING = 'PROCESSING',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  UNKNOWN = 'UNKNOWN'
}

export declare const enum PrinterState {
  READY = 'READY',
  PAUSED = 'PAUSED',
  PRINTING = 'PRINTING',
  UNKNOWN = 'UNKNOWN',
  OFFLINE = 'OFFLINE'
}

export declare function printFile(printerName: string, filePath: string, jobName: string | undefined | null, options: Array<PrintOption>, ghostscript?: GhostscriptConfig | undefined | null): bigint

export interface PrintOption {
  key: string
  value: string
}

export declare function restartJob(printerName: string, jobId: bigint): void

export declare function resumeJob(printerName: string, jobId: bigint): void
