/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getActiveJobs(printerName: string): Array<PrinterJob>

export declare function getDefaultPrinter(): Printer | null

export declare function getJobHistory(printerName: string): Array<PrinterJob>

export declare function getPrinterByName(printerName: string): Printer | null

export declare function getPrinters(): Array<Printer>

export declare function print(printerName: string, buffer: Uint8Array, jobName: string | undefined | null, options: Array<PrintOption>): bigint

export interface Printer {
  name: string
  systemName: string
  driverName: string
  uri: string
  portName: string
  processor: string
  dataType: string
  description: string
  location: string
  isDefault: boolean
  isShared: boolean
  state: PrinterState
  stateReasons: Array<string>
}

export interface PrinterJob {
  id: bigint
  name: string
  state: PrinterJobState
  mediaType: string
  createdAt: Date
  processedAt?: Date
  completedAt?: Date
  printerName: string
}

export declare const enum PrinterJobState {
  PENDING = 'PENDING',
  PAUSED = 'PAUSED',
  PROCESSING = 'PROCESSING',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  UNKNOWN = 'UNKNOWN'
}

export declare const enum PrinterState {
  READY = 'READY',
  PAUSED = 'PAUSED',
  PRINTING = 'PRINTING',
  UNKNOWN = 'UNKNOWN',
  OFFLINE = 'OFFLINE'
}

export declare function printFile(printerName: string, filePath: string, jobName: string | undefined | null, options: Array<PrintOption>): bigint

export interface PrintOption {
  key: string
  value: string
}
